<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__el-id-6146-4</name>
   <tag></tag>
   <elementGuidId>24dc381c-491f-4aa5-bfc8-87ffd1328121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-6146-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-id-6146-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e468d359-293a-499d-8980-a9234df90431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>873d26bb-eb4f-4e62-864f-d624cf392325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelmodifiers</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>6ea5b381-fac3-4725-a625-a24bbf19e69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ee4e510f-93ab-4150-8d68-8448d0c2a366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bab0f97a-969d-4a3f-ab16-e960fc05336e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>30dc9c61-9bdd-4e28-8bd1-11544a286b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>密码</value>
      <webElementGuid>b6d72168-71cb-40b1-98b7-6a022b875da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-id-6146-4</value>
      <webElementGuid>f23ddd59-0b25-4048-99ce-bdf450123803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-6146-4&quot;)</value>
      <webElementGuid>ad98c2c8-38e7-409b-98a4-08b748d9c2b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-id-6146-4']</value>
      <webElementGuid>3fcaa07a-0ba5-49bf-85f0-7fbd82be3e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>6625d363-c9d6-4a83-9ce0-c5178431ef63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>069aaac8-624b-43fc-aca1-6a4026c76001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '密码' and @id = 'el-id-6146-4']</value>
      <webElementGuid>bc5c4682-8eb8-48c3-8e31-8501a97a8585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
