<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SDN_el-id-6146-24</name>
   <tag></tag>
   <elementGuidId>5952c4a0-157c-46eb-aa2c-e9d0f49e867f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-id-6146-24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-id-6146-24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b836f5c-03a1-4915-b069-74d774105092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>329f4ba9-b880-4e3a-8379-dfbb18edbf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e23777af-c227-409d-8eb6-0fb15acf60c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d5c66644-6fc2-488d-a60b-c64f393f1180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5274656b-2206-4db9-b205-6f8b2be2a6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请选择SDN版本号</value>
      <webElementGuid>182cc321-6a0d-4dc9-b514-db454ab4b8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-id-6146-24</value>
      <webElementGuid>a845062b-b94d-4524-936b-56c280ed6527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-6146-24&quot;)</value>
      <webElementGuid>633eaefe-2284-46d0-9518-101d3e3b2cd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-id-6146-24']</value>
      <webElementGuid>030d1a61-ad5b-4ca3-98d8-e672fb987145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/form/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>30bf8a7d-c14d-4930-8e04-d7a8eebc4c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>1ea7d7da-cc06-4f7e-bbf6-6b60dcbdc037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '请选择SDN版本号' and @id = 'el-id-6146-24']</value>
      <webElementGuid>28a8e1d4-62ec-466a-8606-161828ec5a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
