<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__el-radio__inner</name>
   <tag></tag>
   <elementGuidId>47cbc0c8-124c-4a2f-a0dd-bcc9c9b33e1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.el-radio__inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-id-6146-23']/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c82d9d8b-d726-4991-a111-33c84444d6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-radio__inner</value>
      <webElementGuid>a877d0cb-0b74-46b8-a606-9f87df56df7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-id-6146-23&quot;)/label[@class=&quot;el-radio&quot;]/span[@class=&quot;el-radio__input&quot;]/span[@class=&quot;el-radio__inner&quot;]</value>
      <webElementGuid>2ca132d8-0054-48a5-a520-48935ac66c35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-id-6146-23']/label/span/span</value>
      <webElementGuid>ce5571c0-c9c2-4fce-8fc6-3d44cb96a0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>79a21872-6375-4d62-89c1-ea6380ac55de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
