<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>9930e699-f152-4ded-b132-2d6faf6ac2ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.el-button.el-button--danger > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6b504f8-477a-47e3-9e04-7ed980a31993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>下一步</value>
      <webElementGuid>b75a1689-86ca-48bd-9668-8f09c8f52bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;sdn-block&quot;]/div[@class=&quot;footer&quot;]/button[@class=&quot;el-button el-button--danger&quot;]/span[1]</value>
      <webElementGuid>66a852d7-0b16-4576-8eaf-65b9a2c50cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/button[2]/span</value>
      <webElementGuid>e9a127bd-c638-45b8-9826-ca5e58b744ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ArSDN_5.0'])[1]/preceding::span[1]</value>
      <webElementGuid>9590ddca-485b-48c4-8ddd-261dc7f57f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='下一步']/parent::*</value>
      <webElementGuid>5786323d-221d-45c2-aa2b-470f55656a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>17cebcbf-1a31-4058-bd90-8e66d7ef20bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '下一步' or . = '下一步')]</value>
      <webElementGuid>9f1eb8bd-782b-487a-8993-1f73e88761fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
